name: spectral-scaling-laws
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch
  - numpy
  - pip
  - pip:
      - pyyaml
      - tqdm
      - wandb
      - huggingface_hub
      - triton
      - pytest
      - ruff
      - black
